### ISSUE TITLE
Bug detected in the definition of the catch of the reportQuery method in the Connection class

### ISSUE THREAD

**Issue by dlu92** [matchory/elasticsearch#307]
Original:
![Error](https://github.com/matchory/elasticsearch/assets/25955264/a7160cd9-f977-444d-8d64-5d661dd83951)

Error screenshot:
![image](https://github.com/matchory/elasticsearch/assets/25955264/9e813f54-34ad-4548-86c5-f55a0e6c3ba1)

Fix:
![Fix](https://github.com/matchory/elasticsearch/assets/25955264/a3561528-dea7-471f-bf8c-2262bd43801b)

**Comment by Radiergummi** [comment]
This is a syntax error in PHP 7 and below; this library has a minimum version requirement of PHP 8.2.

**Comment by Radiergummi** [comment]
I see how this is a problem in releases <= `2.7.0`.

**Comment by dlu92** [comment]
I understand, it is necessary that you update the required version of PHP in the composer.json

![image](https://github.com/matchory/elasticsearch/assets/25955264/54f39fbe-ec18-4384-8120-6598ee6d169f)

**Comment by Radiergummi** [comment]
I just published version 2.7.2 which fixes this issue. This will be the last release supporting PHP 7 however, so to get future updates, you should migrate to PHP8.

**Comment by dlu92** [comment]
Great thank you very much.
