### ISSUE TITLE
 Declaration of BuildsFluentQueries must be compatible with ExecutesQueries

### ISSUE THREAD

**Issue by mxdfulder** [matchory/elasticsearch#7]
library version 2.2.0 (Beta 1), php 7.3.1, laravel 5.7.29

> PHP Fatal error:  Declaration of Matchory\Elasticsearch\Concerns\BuildsFluentQueries::id(?string $id = NULL): Matchory\Elasticsearch\Concerns\BuildsFluentQueries must be compatible with Matchory\Elasticsearch\Concerns\ExecutesQueries::id(?string $id = NULL): Matchory\Elasticsearch\Concerns\ExecutesQueries in .../vendor/matchory/elasticsearch/src/Query.php on line 37

Can be fixed by deleting all abstract functions from trait /src/Concerns/ExecutesQueries.php

**Comment by Radiergummi** [comment]
Thank you for reporting - those were mostly only helpful during development anyway.
